name: canokey_console
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  url_strategy: ^0.2.0
  url_launcher: ^6.2.6
  file_picker: ^8.0.3
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1
  flutter_nfc_kit: ^3.4.2
  base32: ^2.1.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  convert: ^3.0.1
  logging: ^1.0.2
  percent_indicator: ^4.0.1
  timer_controller: ^1.0.0
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  fixnum: ^1.1.0
  platform_detector: ^0.2.0
  mobile_scanner: ^5.0.2
  flutter_webrtc: ^0.10.3
  zxing2: ^0.2.3
  image: ^4.1.7
  fido2: ^0.0.4
  ccid: ^0.1.1
  device_info_plus: ^10.1.0
  dart_des: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/

flutter_intl:
  enabled: true
