name: Build and Deploy to Netlify

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FLUTTER_VERSION: 3.24.5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rust-src
        target: wasm32-unknown-unknown
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v3
      with:
        channel: stable
        version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: flutter pub get
    - name: Build Web SPA
      run: |
        cargo install flutter_rust_bridge_codegen
        flutter_rust_bridge_codegen build-web --release
        flutter build web --verbose --web-renderer html
    - uses: actions/upload-artifact@v4
      with:
        name: web-spa
        path: build/web/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: web-spa
          path: /tmp/console-build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: /tmp/console-build
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        timeout-minutes: 5
