name: Build and Deploy to Netlify

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FLUTTER_VERSION: 3.24.5

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        key: web-spa-rust-${{ hashFiles('rust/Cargo.toml') }}
        path: |
          rust/target
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rust-src
        target: wasm32-unknown-unknown
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v3
      with:
        channel: stable
        version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: flutter pub get
    - name: Build Rust Library
      run: |
        cargo install flutter_rust_bridge_codegen
        flutter_rust_bridge_codegen build-web --release
    - run: flutter build web --verbose --web-renderer html
    - uses: actions/upload-artifact@v4
      with:
        name: web-spa
        path: build/web/
